### PR TITLE
Fix close from outside click

### PR DESCRIPTION
**Pull request by arnaldovalente**
When click outside the modal or use the X button close of modal title the modal dosen't show anymore.

### CODE REVIEW

**Comment by arnaldovalente** [comment]
Removing wire:ignore.self and new issue, if I have checkbox in modal and I check it close the modal and I can't reopen it.

**Comment by arnaldovalente** [comment]
Now all is fixed, do you now a better way?

**Comment by tsommie** [comment]
I was just reviewing your PR and then it closed...why?

**Comment by arnaldovalente** [comment]
You write me that this not fix the issue!?!
Why do you remove your reply?
I write on first post about issue, I'm beginner but I would help you to fix a issue and I'm sorry if I write something not clearly.

Your reply:
You speak of a livewire issue and then you make a PR with an update on a vue.js file?
Not to mention the update had nothing to do with the issue stated above.

**Comment by tsommie** [comment]
> You write me that this not fix the issue!?!
> Why do you remove your reply?
> I write on first post about issue, I'm beginner but I would help you to fix a issue and I'm sorry if I write something not clearly.
> 
> Your reply:
> You speak of a livewire issue and then you make a PR with an update on a vue.js file?
> Not to mention the update had nothing to do with the issue stated above.

I was replying to another issue from another repository, it was an accident. Sorry about that.

**Comment by arnaldovalente** [comment]
ok, give me few time to make other fix and port few update implemented in original jetstream.
I have also find a way to set focus on first element directly when modal is opened.
https://github.com/laravel/jetstream/compare/2.x...arnaldovalente:patch-1

**Pull request closed without merging**
